CREATE TABLE b_blackbutterfly_seoredirekt
(
	ID INT(11) NOT NULL auto_increment,
	FIRSTURL VARCHAR(255) NOT NULL,
	LASTURL VARCHAR(255) NOT NULL,
	TYPEBLOCK VARCHAR(255) NOT NULL,
	SITEID VARCHAR(255) NOT NULL,
	ADDURLDATE INT(30) NOT NULL,
	USERID INT(11) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE b_blackbutterfly_seoredirektignore
(
	ID INT(11) NOT NULL auto_increment,
	URL VARCHAR(255) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE b_blackbutterfly_seoredirekterror
(
	ID INT(11) NOT NULL auto_increment,
	URL VARCHAR(255) NOT NULL,
	COUNTSETURL INT(11) NOT NULL,
	REFERALURL VARCHAR(255) NULL,
	SITEID VARCHAR(255) NOT NULL,	
	PRIMARY KEY (id)
);