<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetPageProperty("description", "Бренды для маникюра педикюра и мастеров");
$APPLICATION->SetPageProperty("keywords", "производители, бренды, маникюр, производители лаков");
$APPLICATION->SetPageProperty("title", "Производители - Мастера красоты Mehendi24.ru ");
$APPLICATION->SetTitle("Производители");
?>
<? $APPLICATION->IncludeComponent("bitrix:news", "brands", array(
        "IBLOCK_TYPE"                     => "aspro_mshop_content",
        "IBLOCK_ID"                       => "61",
        "NEWS_COUNT"                      => "32",
        "USE_SEARCH"                      => "N",
        "USE_RSS"                         => "N",
        "USE_RATING"                      => "N",
        "USE_CATEGORIES"                  => "N",
        "USE_REVIEW"                      => "N",
        "USE_FILTER"                      => "N",
        "SORT_BY1"                        => "SORT",
        "SORT_ORDER1"                     => "ASC",
        "SORT_BY2"                        => "SORT",
        "SORT_ORDER2"                     => "ASC",
        "CHECK_DATES"                     => "Y",
        "SEF_MODE"                        => "Y",
        "SEF_FOLDER"                      => "/info/brands/",
        "AJAX_MODE"                       => "N",
        "AJAX_OPTION_JUMP"                => "N",
        "AJAX_OPTION_STYLE"               => "Y",
        "AJAX_OPTION_HISTORY"             => "N",
        "CACHE_TYPE"                      => "A",
        "CACHE_TIME"                      => "36000000",
        "CACHE_FILTER"                    => "N",
        "CACHE_GROUPS"                    => "N",
        "SET_TITLE"                       => "Y",
        "SET_STATUS_404"                  => "N",
        "INCLUDE_IBLOCK_INTO_CHAIN"       => "N",
        "ADD_SECTIONS_CHAIN"              => "N",
        "USE_PERMISSIONS"                 => "N",
        "PREVIEW_TRUNCATE_LEN"            => "",
        "LIST_ACTIVE_DATE_FORMAT"         => "j F Y",
        "LIST_FIELD_CODE"                 => array(
            0 => "PREVIEW_PICTURE",
            1 => "DETAIL_PICTURE",
            2 => "",
        ),
        "LIST_PROPERTY_CODE"              => array(
            0 => "",
            1 => "",
        ),
        "HIDE_LINK_WHEN_NO_DETAIL"        => "N",
        "DISPLAY_NAME"                    => "Y",
        "META_KEYWORDS"                   => "-",
        "META_DESCRIPTION"                => "-",
        "BROWSER_TITLE"                   => "-",
        "DETAIL_ACTIVE_DATE_FORMAT"       => "j F Y",
        "DETAIL_FIELD_CODE"               => array(
            0 => "PREVIEW_PICTURE",
            1 => "",
        ),
        "DETAIL_PROPERTY_CODE"            => array(
            0 => "",
            1 => "MORE_PHOTO",
            2 => "",
        ),
        "IBLOCK_CATALOG_TYPE"             => "aspro_mshop_catalog",
        "CATALOG_IBLOCK_ID1"              => "66",
        "CATALOG_IBLOCK_ID2"              => "",
        "CATALOG_IBLOCK_ID3"              => "",
        "SHOW_BACK_LINK"                  => "Y",
        "GALLERY_PROPERTY"                => "MORE_PHOTO",
        "SHOW_GALLERY"                    => "Y",
        "LINKED_PRODUCTS_PROPERTY"        => "CML2_MANUFACTURER",
        "SHOW_LINKED_PRODUCTS"            => "Y",
        "DETAIL_DISPLAY_TOP_PAGER"        => "N",
        "DETAIL_DISPLAY_BOTTOM_PAGER"     => "Y",
        "DETAIL_PAGER_TITLE"              => "",
        "DETAIL_PAGER_TEMPLATE"           => "",
        "DETAIL_PAGER_SHOW_ALL"           => "Y",
        "PAGER_TEMPLATE"                  => ".default",
        "DISPLAY_TOP_PAGER"               => "N",
        "DISPLAY_BOTTOM_PAGER"            => "Y",
        "PAGER_TITLE"                     => "",
        "PAGER_SHOW_ALWAYS"               => "N",
        "PAGER_DESC_NUMBERING"            => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL"                  => "N",
        "CATALOG_FILTER_NAME"             => "arrProductsFilter",
        "AJAX_OPTION_ADDITIONAL"          => "",
        "COMPONENT_TEMPLATE"              => "brands",
        "SET_LAST_MODIFIED"               => "N",
        "ADD_ELEMENT_CHAIN"               => "N",
        "DETAIL_SET_CANONICAL_URL"        => "N",
        "PAGER_BASE_LINK_ENABLE"          => "N",
        "SHOW_404"                        => "N",
        "MESSAGE_404"                     => "",
        "SEF_URL_TEMPLATES"               => array(
            "news"    => "",
            "section" => "",
            "detail"  => "#ELEMENT_CODE#/",
        )
    ), false); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>